name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar sistema
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk

      - name: Instalar buildozer
        run: pip install buildozer cython

      - name: Inicializar
        run: buildozer init

      - name: Configurar app
        run: |
          sed -i 's/title = .*/title = CodUn/' buildozer.spec
          sed -i 's/package.name = .*/package.name = codun/' buildozer.spec
          sed -i 's/requirements = .*/requirements = python3,kivy/' buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
