name: Generar APK de Android
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar dependencias de Android
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake libffi-dev libgdbm-dev bluez libasound2-dev libsqlite3-dev

      - name: Compilar con Buildozer
        uses: ArtemGovorov/buildozer-action@v1
        with:
          command: buildozer -v android debug
          buildozer_version: stable

      - name: Guardar archivo APK
        uses: actions/upload-artifact@v4
        with:
          name: Mi-Aplicacion-APK
          path: bin/*.apk
