name: Generar ejecutable
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install pyinstaller kivy kivymd

      - name: Generar ejecutable
        run: pyinstaller --onefile Buscador.py

      - name: Subir ejecutable
        uses: actions/upload-artifact@v2
        with:
          name: BuscadorExe
          path: dist/Buscador.exe
